### ISSUE TITLE
Tag v1.2.2

### ISSUE THREAD

**Issue by seamus-oconnor** [myna/myna-js#2]
We would like to use v1.2.2 via bower in our project but currently there is only a tag for the 2.1 release.

Github can't handle a PR that with just tags. You guys will need to run the following:

`git tag -a v1.2.2 2a4c81326adab1a4473d9e151308a964b556d36f -m "Tagging old release" && git push --tags`

**Comment by noelwelsh** [comment]
Sorry for the delay -- wasn't subscribed to notifications so I missed this. I've pushed the tag you requested.
